# -*- coding: utf-8 -*-
"""datavizcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wLyF3X9079yRaNBikORepZ8jEwhIsBG
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# ---------------------------------------------------------
# Configuración básica de la página
# ---------------------------------------------------------
st.set_page_config(
    page_title="University Student Analytics",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------------
# Carga y preparación de datos
# ---------------------------------------------------------
@st.cache_data
def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    # normalizar nombres de columnas
    df.columns = [c.strip().lower() for c in df.columns]

    # calcular retention_rate si no existe y tenemos retained + enrolled
    if "retention_rate" not in df.columns:
        if {"retained", "enrolled"}.issubset(df.columns):
            df["retention_rate"] = np.where(
                df["enrolled"] > 0,
                df["retained"] / df["enrolled"],
                np.nan
            )
        else:
            df["retention_rate"] = np.nan

    # normalizar term, department y year si existen
    if "term" in df.columns:
        df["term"] = df["term"].astype(str).str.strip().str.title()

    if "department" in df.columns:
        df["department"] = df["department"].astype(str).str.strip()

    if "year" in df.columns:
        df["year"] = pd.to_numeric(df["year"], errors="coerce")

    return df

DATA_PATH = "university_student_data.csv"  # mismo nombre que tu archivo
df = load_data(DATA_PATH)

# ---------------------------------------------------------
# Sidebar: filtros
# ---------------------------------------------------------
with st.sidebar:
    st.header("🔎 Filters")

    # Años
    if "year" in df.columns:
        year_values = sorted(df["year"].dropna().unique().tolist())
        year_sel = st.multiselect(
            "Year",
            options=year_values,
            default=year_values
        )
    else:
        year_sel = None

    # Departamento
    if "department" in df.columns:
        dept_values = sorted(
            [d for d in df["department"].dropna().unique().tolist() if d != ""]
        )
        if len(dept_values) > 0:
            dept_sel = st.multiselect(
                "Department",
                options=dept_values,
                default=dept_values
            )
        else:
            st.info("No department values found in dataset.")
            dept_sel = None
    else:
        dept_sel = None

    # Term (Spring/Fall, etc.)
    if "term" in df.columns:
        term_values = sorted(df["term"].dropna().unique().tolist())
        term_sel = st.multiselect(
            "Term",
            options=term_values,
            default=term_values
        )
    else:
        term_sel = None

# ---------------------------------------------------------
# Aplicar filtros
# ---------------------------------------------------------
mask = pd.Series(True, index=df.index)

if year_sel is not None and len(year_sel) > 0:
    mask &= df["year"].isin(year_sel)

if dept_sel is not None and len(dept_sel) > 0 and "department" in df.columns:
    mask &= df["department"].isin(dept_sel)

if term_sel is not None and len(term_sel) > 0 and "term" in df.columns:
    mask &= df["term"].isin(term_sel)

fdf = df[mask].copy()

# Si no queda data después de filtrar, avisar y salir
if fdf.empty:
    st.error("No data available for the selected filters. Try selecting more years / terms / departments.")
    st.stop()

# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.title("📊 University Student Analytics")
st.caption("Admissions • Enrollment • Retention — Interactive Dashboard")

# ---------------------------------------------------------
# KPI Cards (al menos 3 indicadores)
# ---------------------------------------------------------
col1, col2, col3 = st.columns(3)

with col1:
    if "enrolled" in fdf.columns:
        total_enrolled = int(fdf["enrolled"].sum())
        st.metric("Total Enrolled (filtered)", f"{total_enrolled:,}")
    else:
        st.metric("Total Enrolled", "N/A")

with col2:
    if "retention_rate" in fdf.columns:
        avg_ret = fdf["retention_rate"].mean()
        st.metric("Avg Retention Rate", f"{avg_ret*100:.1f}%" if not np.isnan(avg_ret) else "N/A")
    else:
        st.metric("Avg Retention Rate", "N/A")

with col3:
    # Si existe `applications` u otra métrica, úsala; si no, usa número de registros
    if "applications" in fdf.columns:
        total_app = int(fdf["applications"].sum())
        st.metric("Total Applications (filtered)", f"{total_app:,}")
    else:
        st.metric("Records (filtered rows)", f"{len(fdf):,}")

st.markdown("---")

# ---------------------------------------------------------
# 1) Line chart: Retention rate over time
# ---------------------------------------------------------
if {"year", "retention_rate"}.issubset(fdf.columns):
    trend = (
        fdf.groupby("year", as_index=False)["retention_rate"]
           .mean()
           .sort_values("year")
    )
    fig_trend = px.line(
        trend,
        x="year",
        y="retention_rate",
        title="Retention Rate — Trend Over Time",
        markers=True
    )
    fig_trend.update_layout(yaxis_tickformat=".0%")
    st.plotly_chart(fig_trend, use_container_width=True)
else:
    st.info("Retention trend requires columns: 'year' and 'retention_rate'.")

# ---------------------------------------------------------
# 2) Bar chart: Enrollment by Term (Spring vs Fall)
# ---------------------------------------------------------
if {"term", "enrolled"}.issubset(fdf.columns):
    term_grp = (
        fdf.groupby("term", as_index=False)["enrolled"]
           .sum()
           .sort_values("enrolled", ascending=False)
    )
    c1, c2 = st.columns(2)

    with c1:
        fig_term_bar = px.bar(
            term_grp,
            x="term",
            y="enrolled",
            title="Enrollment by Term",
            text_auto=True
        )
        st.plotly_chart(fig_term_bar, use_container_width=True)

    with c2:
        fig_term_pie = px.pie(
            term_grp,
            names="term",
            values="enrolled",
            title="Term Distribution (Enrollment Share)"
        )
        st.plotly_chart(fig_term_pie, use_container_width=True)
else:
    st.info("Term comparison requires columns: 'term' and 'enrolled'.")

# ---------------------------------------------------------
# 3) Line / bar chart: Enrollment by Department & Year
# ---------------------------------------------------------
if {"department", "year", "enrolled"}.issubset(fdf.columns) and fdf["department"].notna().any():
    st.markdown("### Enrollment by Department and Year")

    dept_year = (
        fdf.groupby(["department", "year"], as_index=False)["enrolled"]
           .sum()
    )
    fig_dept = px.line(
        dept_year,
        x="year",
        y="enrolled",
        color="department",
        markers=True,
        title="Enrollment by Department & Year"
    )
    st.plotly_chart(fig_dept, use_container_width=True)
else:
    st.info("Department trend requires: 'department', 'year', and 'enrolled'.")

# ---------------------------------------------------------
# Footer
# ---------------------------------------------------------
st.caption("Data Mining — Universidad de la Costa • Dashboard by Juan Bolívar Ferrer")