# -*- coding: utf-8 -*-
"""dataviz_dashboard_juan_bolivar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4etQNF866ReBGumbwm4pAgG_UNNSV6a
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

st.set_page_config(page_title="University Student Analytics", page_icon="📊", layout="wide")

@st.cache_data
def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Normalize column names
    df.columns = [c.strip().lower() for c in df.columns]

    # Harmonize expected columns (edit if your CSV uses different names)
    # Required: year, department, term, enrolled, retained OR retention_rate, satisfaction_score
    # If retention_rate missing, compute from retained/enrolled
    if "retention_rate" not in df.columns:
        if {"retained","enrolled"}.issubset(df.columns):
            df["retention_rate"] = np.where(df["enrolled"] > 0, df["retained"] / df["enrolled"], np.nan)
        else:
            df["retention_rate"] = np.nan

    # If satisfaction is in 1–100 scale, normalize to 1–5 (optional)
    if "satisfaction_score" in df.columns:
        # leave as-is; you can rescale if needed:
        # df["satisfaction_score"] = df["satisfaction_score"] / 20.0
        pass

    # Clean term values
    if "term" in df.columns:
        df["term"] = df["term"].astype(str).str.strip().str.title()

    # Ensure year numeric
    if "year" in df.columns:
        df["year"] = pd.to_numeric(df["year"], errors="coerce")

    return df

# ---- Load ----
DATA_PATH = "university_student_data.csv"  # or a raw GitHub URL
df = load_data(DATA_PATH)

# ---- Sidebar Filters ----
with st.sidebar:
    st.header("🔎 Filters")
    years = sorted([int(y) for y in df["year"].dropna().unique()]) if "year" in df.columns else []
    depts = sorted(df["department"].dropna().unique()) if "department" in df.columns else []
    terms = sorted(df["term"].dropna().unique()) if "term" in df.columns else []

    year_sel = st.multiselect("Year", options=years, default=years)
    dept_sel = st.multiselect("Department", options=depts, default=depts)
    term_sel = st.multiselect("Term", options=terms, default=terms)

# ---- Apply Filters ----
mask = pd.Series(True, index=df.index)
if years and year_sel:
    mask &= df["year"].isin(year_sel)
if depts and dept_sel:
    mask &= df["department"].isin(dept_sel)
if terms and term_sel:
    mask &= df["term"].isin(term_sel)

fdf = df[mask].copy()

# ---- Header ----
st.title("📊 University Student Analytics")
st.caption("Admissions • Enrollment • Retention • Satisfaction — Interactive Dashboard")

# ---- KPI Cards ----
col1, col2, col3 = st.columns(3)
with col1:
    total_enrolled = int(fdf["enrolled"].sum()) if "enrolled" in fdf.columns else None
    st.metric("Total Enrolled", f"{total_enrolled:,}" if total_enrolled is not None else "—")
with col2:
    avg_ret = fdf["retention_rate"].mean() if "retention_rate" in fdf.columns else np.nan
    if pd.notna(avg_ret):
        st.metric("Avg Retention Rate", f"{avg_ret*100:.1f}%")
    else:
        st.metric("Avg Retention Rate", "—")
with col3:
    avg_sat = fdf["satisfaction_score"].mean() if "satisfaction_score" in fdf.columns else np.nan
    st.metric("Avg Satisfaction", f"{avg_sat:.2f}" if pd.notna(avg_sat) else "—")

st.markdown("---")

# ---- 1) Retention Trend Over Time ----
if {"year","retention_rate"}.issubset(fdf.columns):
    trend = (
        fdf.groupby("year", as_index=False)["retention_rate"]
           .mean()
           .sort_values("year")
    )
    fig1 = px.line(trend, x="year", y="retention_rate",
                   title="Retention Rate — Trend Over Time",
                   markers=True)
    fig1.update_layout(yaxis_tickformat=".0%")
    st.plotly_chart(fig1, use_container_width=True)
else:
    st.info("Retention trend requires columns: year, retention_rate (or retained & enrolled).")

# ---- 2) Satisfaction by Year ----
if {"year","satisfaction_score"}.issubset(fdf.columns):
    sat = (
        fdf.groupby("year", as_index=False)["satisfaction_score"]
           .mean()
           .sort_values("year")
    )
    fig2 = px.bar(sat, x="year", y="satisfaction_score",
                  title="Average Student Satisfaction by Year")
    st.plotly_chart(fig2, use_container_width=True)
else:
    st.info("Satisfaction chart requires: year, satisfaction_score.")

# ---- 3) Spring vs Fall Comparison ----
if {"term","enrolled"}.issubset(fdf.columns):
    term_cmp = (
        fdf.groupby("term", as_index=False)["enrolled"]
           .sum()
           .sort_values("enrolled", ascending=False)
    )
    left, right = st.columns(2)
    with left:
        fig3 = px.bar(term_cmp, x="term", y="enrolled",
                      title="Enrollment by Term (Spring vs Fall)")
        st.plotly_chart(fig3, use_container_width=True)
    with right:
        fig4 = px.pie(term_cmp, names="term", values="enrolled",
                      title="Term Distribution (Enrollment Share)")
        st.plotly_chart(fig4, use_container_width=True)
else:
    st.info("Term comparison requires: term, enrolled.")

# ---- Optional: Department Detail ----
if {"department","year","enrolled"}.issubset(fdf.columns):
    st.markdown("### Department Enrollment by Year")
    dept_year = (
        fdf.groupby(["department","year"], as_index=False)["enrolled"]
           .sum()
    )
    fig5 = px.line(dept_year, x="year", y="enrolled", color="department",
                   markers=True, title="Enrollment by Department & Year")
    st.plotly_chart(fig5, use_container_width=True)

# ---- Footer ----
st.caption("Data Mining — Universidad de la Costa • Streamlit Dashboard")